<a href="https://colab.research.google.com/github/anyaconda/myNumerai/blob/main/Numerai_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#meta 03/20/2021 Numerai Interactive Tutorial - First Submission, Linear
#src https://numer.ai/submit

#history
#03/20/2021 LINEAR ROUND 256
#     Model anyaconda_linear

# Making your first submission on Numerai

## Introduction 
This tutorial will go over how to create your first submission on Numerai.

## Overview

1. Using this notebook
2. Download the datasets
3. Train your first model
4. Generate your first predictions
4. Make your first submission


---


## 1. Using this notebook 

This is an interactive notebook. You can execute code in each cell by pressing `shift+enter`. This requires you to login with your Google account.

In order to make changes, you need to make a copy by `File -> Save a copy in Drive`.

Let's start off by installing and importing our dependencies.

In [1]:
# install dependencies
!pip install pandas sklearn numerapi

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (0.0)
Collecting numerapi
  Downloading https://files.pythonhosted.org/packages/fd/96/ebdbaff5a2fef49b212e4f40634166f59e45462a768c0136d148f00255c5/numerapi-2.4.5-py3-none-any.whl
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn) (0.22.2.post1)
Requirement already satisfied: tqdm>=4.29.1 in /usr/local/lib/python3.7/dist-packages (from numerapi) (4.41.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from numerapi) (7.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from numerapi) (2.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.0.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->numerapi) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->numerapi) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->numerapi) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->numerapi) (2020.12.5)
Installing collected packages: numerapi
Successfully installed numerapi-2.4.5

In [2]:
# import dependencies
import pandas as pd
import numerapi
import sklearn.linear_model

## 2. Download the datasets

### Datasets 
*   `training_data` is used to train your model
*   `tournament_data` is used to evaluate your model

### Column descriptions
*   id: a randomized id that corresponds to a stock 
*   era: a period of time
*   data_type: either `train`, `validation`, `test`, or `live` 
*   feature_*: abstract financial features of the stock 
*   target: abstract measure of stock performance

In [3]:
# download the latest training dataset (takes around 30s)
training_data = pd.read_csv("https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_training_data.csv.xz")
training_data.head()

                 id   era data_type  ...  feature_wisdom45  feature_wisdom46  target
0  n000315175b67977  era1     train  ...              0.50              0.75    0.50
1  n0014af834a96cdd  era1     train  ...              0.25              1.00    0.25
2  n001c93979ac41d4  era1     train  ...              0.25              0.75    0.25
3  n0034e4143f22a13  era1     train  ...              1.00              1.00    0.25
4  n00679d1a636062f  era1     train  ...              0.25              0.75    0.75

[5 rows x 314 columns]

In [4]:
# download the latest tournament dataset (takes around 30s)
tournament_data = pd.read_csv("https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_tournament_data.csv.xz")
tournament_data.head()

                 id     era  ... feature_wisdom46  target
0  n0003aa52cab36c2  era121  ...             0.00    0.25
1  n000920ed083903f  era121  ...             0.50    0.50
2  n0038e640522c4a6  era121  ...             0.00    1.00
3  n004ac94a87dc54b  era121  ...             0.25    0.50
4  n0052fe97ea0c05f  era121  ...             1.00    0.75

[5 rows x 314 columns]

In [15]:
training_data.shape, tournament_data.shape

((501808, 314), (1676742, 314))

## 3. Train your first model
Let's create a basic model using sklearn's linear regression.

In [5]:
# find only the feature columns
feature_cols = training_data.columns[training_data.columns.str.startswith('feature')]

In [6]:
# select those columns out of the training dataset
training_features = training_data[feature_cols]

In [7]:
# create a model and fit the training data (~30 sec to run)
model = sklearn.linear_model.LinearRegression()
model.fit(training_features, training_data.target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## 4. Generate your first predictions
Now that we have a trained model, we can use it to make predictions on the tournament data.

In [8]:
# select the feature columns from the tournament data
live_features = tournament_data[feature_cols]

In [9]:
# predict the target on the live features
predictions = model.predict(live_features)

In [10]:
# predictions must have an `id` column and a `prediction` column
predictions_df = tournament_data["id"].to_frame()
predictions_df["prediction"] = predictions
predictions_df.head()

                 id  prediction
0  n0003aa52cab36c2    0.481608
1  n000920ed083903f    0.492837
2  n0038e640522c4a6    0.530817
3  n004ac94a87dc54b    0.497083
4  n0052fe97ea0c05f    0.503089

## 5. Make your first submission
To enter the tournament, we must submit the predictions back to Numerai. We will use the `numerapi` library to do this.

In [16]:
# Get your API keys and model_id from https://numer.ai/notebook
public_id = "REPLACEME"
secret_key = "REPLACEME"
model_id = "be449467"
napi = numerapi.NumerAPI(public_id=public_id, secret_key=secret_key)

In [17]:
# Upload your predictions
predictions_df.to_csv("predictions.csv", index=False)
submission_id = napi.upload_predictions("predictions.csv", model_id=model_id)

2021-03-21 06:34:47,649 INFO numerapi.base_api: uploading predictions...

# Done 🚀
Good job! You just made your first submission on Numerai!

Head back over to https://numer.ai/notebook to continue.